[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
# Ensure devDependencies are installed for the build step
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
# Install all deps (including dev) during build image
NPM_CONFIG_PRODUCTION = 'false'
NODE_ENV = 'production'
PORT = '3000'